### ISSUE TITLE
Restive.js in cross-domain iframe error

### ISSUE THREAD

**Issue by warcode** [obihill/restive.js#20]
When embedding a page that uses restive.js from an external domain; example.com hosts the restive webpage, test.net hosts an iframe that embeds example.com, restive attempts to access the parent window and is denied access. This causes javascript processing to error.

Happens at storage creation, and presumably whenever it attempts to access window.parent.

    //Create window storage
    window.rstv_store = {'main': {}};
    window.parent.rstv_store = {'main': {}};

**Comment by pkenterlis** [comment]
Has this been resolved? I am experiencing errors when attempting to display a site inside a cross-origin iframe. I don't need to communicate any data between them. Is there a solution?

**Comment by obihill** [comment]
Hi Panagiotis,

Can you provide some code so I can take a closer look?

**Comment by jwmuserjp** [comment]
The problem persists in 2020. When a page that uses your library is referenced within an iframe a cross origin error is displayed.

**Comment by obihill** [comment]
@jwmuserjp Thanks for the update on this. I just added this to the TODO for fixes to explore. As we have a major release of a completely revamped restive.js [with a new name, hopefully in the summer, G-d willing] coming up, if it can be fixed it'll be fixed by then.

Cheers.
