### ISSUE TITLE
Restivejs doesn't work on mobile - body tag stays empty on mobile phone

### ISSUE THREAD

**Issue by kansas3d** [obihill/restive.js#22]
Thanks restivejs looks really good.
Everything works for me when I resize my PC browser. 
But when I load the website on my iphone it doesn't work at all.
My body tag stays empty on the iphone.

This is the code I used:

	$(document).ready(function () {
            $('body').restive({
	      breakpoints: ['240', '320', '480', '640-p', '640-l', '960'],
	      classes: ['css-240', 'css-320', 'css-480', 'css-640-p', 'css-640-l', 'css-960']
		  });
      });

And when I'm adding turbo_classes:'is_portrait=portrait,is_landscape=landscape,is_mobile=mobi,is_phone=phone,is_tablet=tablet'
then my browser shows this in the body tag of my browser on my PC:

body class="portrait function (){return h} Array() { [native code] } (b,a){Array.forEach(this,b,a);return this} (){for(var b=this.length, a=Array(b);b--;)a[b]=q(this[b]);return a} this.filter(function(b){return null!=b})} (b){var a=Array.slice(arguments,1);return this.map(function(c){return c[b].apply(c,a)})} (b){for(var a={},c=Math.min(this.length,b.length),d=0;d<c;d++)a[b[d]]=this[d];return a={},c=0,d=this.length;c<d;c++)for(var e in b)if(b[e](this[c])){a[e]=this[c];delete b[e];break}return (b,a){return-1!=this.indexOf(b,a)} (b){this.push.apply(this,b);return this.length?this[this.length-1]:null} this.length?this[Number.random(0,this.length-1)]:null} (b){this.contains(b)||this.push(b);return a=0,c=b.length;a<c;a++)this.include(b[a]);return a=this.length;a--;)this[a]===b&amp;&amp;this.splice(a,1);return i=0;i<=this.length;i++){this.shift();}} b=[],a=0,c=this.length;a<c;a++){var d=typeOf(this[a]);&quot;null&quot;!=d&amp;&amp;(b=b.concat(&quot;array&quot;==d||&quot;collection&quot;==d||&quot;arguments&quot;==d||instanceOf(this[a],Array)?Array.flatten(this[a]):this[a]))}return b} b=0,a=this.length;b<a;b++)if(null!=this[b])return this[b];return null} (b){if(3!=this.length)return null;var a=this.map(function(b){1==b.length&amp;&amp;(b+=b);return b.toInt(16)});return b?a:&quot;rgb(&quot;+a+&quot;)&quot;} (b){if(3>this.length)return null; if(4==this.length&amp;&amp;0==this[3]&amp;&amp;!b)return&quot;transparent&quot;;for(var a=[],c=0;3>c;c++){var d=(this[c]-0).toString(16);a.push(1==d.length?&quot;0&quot;+d:d)}return b?a:&quot;#&quot;+a.join(&quot;&quot;)} i=1;i<this.length;i++){if(this[i][0]==this[i-1][0]){this.splice(i,1);}}} css-320"

But the body tag on the iphone is still empty and just shows: body

Would be great if you would know why.

Thanks :)

**Comment by obihill** [comment]
I'm so sorry, this response is coming really late, but I'm curious to know if you solved this issue?

The latest version of Restive.JS has a few updates that I believe rectify the issue you were having.

Cheers.

**Comment by kansas3d** [comment]
No worries.
I couldn't get it run properly on Joomla anymore.
I'm using media queries instead now.

But great news, thanks for the updates. I'll keep using it in some later project for sure again.
I'll let you know then if it's working with Joomla too :)
Thanks

**Comment by obihill** [comment]
You're welcome. We'll keep working to improve Restive.JS so we have less and less issues.

I'll close this, but if you ever have any issue like this again, please feel free to reopen.

Cheers.

**Comment by lukdeboss** [comment]
Hi guys,
I've dig many internet pages, try to find example but found nothing useful for restive.js
I am sure it is great piece of soft but without proper working example where you can start working with it is in many cases useless.
if I would be able to find simple but full and ready to use example I would be happy to learn but until now I have just only many not functional snippets.
If you are aware of any good examples please share
