### ISSUE TITLE
max-width emulation

### ISSUE THREAD

**Issue by Narayon** [obihill/restive.js#24]
Great plugin!
Is there a way to maintain the classes of the breakpoints after passing the corresponding width? I want to emulate the max-width behavior of the media queries. 
For example, if I have 2 breakpoints - 500 and 700 - is there a way to maintain the 700 breakpoint class when the device gets to 500 width, so it will show the 500 class and the 700 class?
I want to change something at 700 breakpoint and keep it like for any width below that.

Thank you.

**Comment by obihill** [comment]
If you're trying to emulate the following:

```
@media only screen and (max-width: 700px)  {...}
```

Then your Restive.JS Constructor should look like this:

```
    $(document).ready(function () {
        $('body').restive({
            breakpoints: ['700'],
            classes: ['css-700'],
            force_dip: true            
        });
    });
```

This will create a breakpoint range of 0 - 700 pixels, and it will apply the class `css-700` [which you can change to whatever you want] to the body tag, only if the device width falls within that range. `force_dip` will tell Restive.JS to use device-independent pixels as the standard of measure (the same behavior as Media Queries).

Is this what you wanted?

**Comment by Narayon** [comment]
Yeah, but with multiple breakpoints. If I add another breakpoint:
```javascript
$(document).ready(function () {
        $('body').restive({
            breakpoints: ['500','700'],
            classes: ['css-500','css-700'],
            force_dip: true            
        });
    });
```
You get 0-500 range to css-500 and 500-700 to css-700. I want 0-500 and 0-700, like css do with `@max-width`.
I work around it doing:

```javascript
$(document).ready(function () {
        $('body').restive({
            breakpoints: ['500','700'],
            classes: ['css-500 css-700','css-700'],
            force_dip: true            
        });
    });
```
But is not very elegant. Doing with multiple instances of restive to diferent elements isn't either.
Maybe use a diferent sufix for this situation. Something like:
```javascript
$(document).ready(function () {
        $('body').restive({
            breakpoints: ['500','700-mx'],
            classes: ['css-500','css-700'],
            force_dip: true            
        });
    });
```
Similar to the orientation markers.

**Comment by obihill** [comment]
In that case, use multiple constructors like this:

```javascript
$(document).ready(function () {
    $.restive.startMulti();

    $('body').restive({
        breakpoints: ['500'],
        classes: ['css-500'],
        force_dip: true            
    });

    $('body').restive({
        breakpoints: ['700'],
        classes: ['css-700'],
        force_dip: true            
    });

    $.restive.endMulti();
});

```

Restive.JS should select the best match in the way you have described.

And if that doesn't work for you, you can do it the old-fashioned way like this:

```javascript
$(document).ready(function () {
    if(Restive.pixelW() <= 500)
    {
        $.('body').addClass('css-500');
    }
    else if(Restive.pixelW() <= 700)
    {
        $.('body').addClass('css-700');
    }
});
```
