### ISSUE TITLE
Initial Install > Results in console but no classes

### ISSUE THREAD

**Issue by patowod** [obihill/restive.js#25]
HI there,
 
your plugin sounds great and I went off implementing it the way described in the docs. Strangely I get console output via firebug but no classes are added to the body tag. Do you have any idea what I am missing? 

Got my initial structure under this url so you can view the code directly: 
http://bit.ly/1DooXtV

I'd really appreciate a hint or two in the right direction.
Thank you in advance, patowod

**Comment by obihill** [comment]
You haven’t defined a viewport meta tag.

**Comment by patowod** [comment]
Thanks a lot! @obihill  
Adding "<meta name="viewport" content="width=device-width, initial-scale=1">" to the head did the trick.
