### ISSUE TITLE
Events outside of $('body').restive({ });

### ISSUE THREAD

**Issue by rnicholls** [obihill/restive.js#26]
Is there a way to access the events outside of the $('body').restive({ }); ?

**Comment by obihill** [comment]
Hi Ronald,

I'm not sure I get your question. Can you provide some more information.

**Comment by rnicholls** [comment]
Basically the same way you can do $.restive.isPhone. 

Just wondering if there is a way to do that but with say, $.restive.onAddClass

**Comment by obihill** [comment]
Ok., Got it. No, it's not possible right now. I didn't envisage anyone would want to use it that way. Any reason why you would prefer this instead of using the `$().restive({})` constructor?
