### ISSUE TITLE
TypeError: this.prop is not a function

### ISSUE THREAD

**Issue by sajaddp** [obihill/restive.js#27]
Hello,
I insert this code to my page:
`	<script type="text/javascript" src="js/restive.min.js"></script>
<script>
$(document).ready(function () {
    $('body').restive({
        breakpoints: ['768', '922'],
        classes: ['css-768', 'css-922']
    });
});
</script>`
and add two class to my css file:
`.css-768{
/*some code*/
}
.css-922{
/*some code*/
}`
but when I refresh page I got this error msg:
TypeError: this.prop is not a function

what is wrong?!

**Comment by obihill** [comment]
Hello Sajad,

Have you included JQuery?

**Comment by sajaddp** [comment]
TNX,
my JQuery address was wrong ):

**Comment by obihill** [comment]
No problem. Glad it's working now. Cheers.
