### ISSUE TITLE
[firefox] "SecurityError: The operation is insecure" alert.

### ISSUE THREAD

**Issue by freshdevelop** [obihill/restive.js#28]
When I include restive.js on my html+css static files it throws the error opening a javascript alert popup that cannot be closed. The error occurs only on firefox and in every page, no matter if I delete all the content or the restive() init call.

**Comment by freshdevelop** [comment]
[update] now it works again. It broke without doing anything and it went back up the same way.

**Comment by obihill** [comment]
Thanks for your feedback.

I'm going to have to see how your code is setup so I can try to recreate your issue and debug (if necessary).

Could you setup a [CodePen](http://codepen.io) or [JSFiddle](https://jsfiddle.net/)?

**Comment by freshdevelop** [comment]
I stripped out all the html and made a [jsfiddle](https://jsfiddle.net/qr9Lrv66/)
Oddly, the issue comes and goes (worked well for two days, now it's back. Console says "exception: out of memory"), and happens only on html static files called with file:/// on Firefox.

**Comment by obihill** [comment]
Thanks. I just ran your jsfiddle and I see a long list of warnings and errors in the console log. However, I don't see one that points to restive.min.js.

When you get the "out of memory" exception, does it actually point to restive.min.js? Does the console point to any specific script? Also, what browser are you using to test?

**Comment by freshdevelop** [comment]
The code occurs only when I include the restive script. If i trim out the <script type="text/javascript" src="js/vendor/restive.min.js"></script> it starts working again.
I'm testing it on Firefox (latest version), Chrome (latest version), IE 11.
The logged console error is not specific to a file.

(meanwhile, it started working again and I did have done anything. I am puzzled)

**Comment by obihill** [comment]
It might be an issue with the combination of scripts, not necessarily restive.min.js on it's own. Ensure that you have restive.min.js directly after jquery.

Do you get the "out of memory" error on each of those 3 browsers?

**Comment by freshdevelop** [comment]
No, it happens only on Firefox.

**Comment by obihill** [comment]
Doing a Google search on "Firefox out of memory exception" seems to point to some scenarios where Chrome has no issue but FIrefox does.

Can you run just jquery and restive.min.js (i.e. remove or comment out all the other scripts) and see if the issue persists?

**Comment by obihill** [comment]
Hi freshdevelop,

I haven't heard back from you on this. We're you able to get things working? 

I'll close this for now, but please open if you still have issues.
