### ISSUE TITLE
Force Switch to Desktop view

### ISSUE THREAD

**Issue by richardNorthwind** [obihill/restive.js#30]
Is there a way to get the mobile display (viewport < 600) switch to full desktop display via the restive call?  (i.e., if I'm using turbo classes like "mobi" and "phone" on mobile display, is there a way to remove those classes from the body tag when a certain link to "switch views" is clicked)?

**Comment by obihill** [comment]
Not natively within Restive. However, I'm sure you can use JQuery to remove the class when a button is clicked. For example:

```javascript
$( ".your_link_selector" ).on( "click", function() {
  $("body").removeClass('mobi');
});
```

Is this what you wanted to achieve?

**Comment by richardNorthwind** [comment]
Yes this is what I was asking about, however when I tried it it doesn’t seem to be working.



Not natively within Restive. However, I'm sure you can use JQuery to remove the class when a button is clicked. For example:

$( ".your_link_selector" ).on( "click", function() {
  $("body").removeClass('mobi');
});

Is this what you wanted to achieve?

**Comment by obihill** [comment]
I just tried a test and it works:

Here's what I put in my `<head>`:

```javascript
<script type="text/javascript" src="path/to/jquery.min.js"></script>
<script type="text/javascript" src="path/to/restive.min.js"></script>
<script>
$(document).ready(function() {

    var elem_body = $('body');
    elem_body.restive({
        breakpoints: ['320', '480', '640', '720', '960', '1280'],
        classes: ['320-c', '480-c', '640-c', '720-c', '960-c', '1280-c'],
        force_dip: true,
        turbo_classes: 'is_mobile=mobi,is_tablet=tablet,is_phone=phone,is_portrait=portrait,is_landscape=landscape'
    });

    $('a.link_1').on('click', function(event){
        event.preventDefault();
        elem_body.removeClass("mobi phone");
    });
});
</script>
```

And here's what's in my `<body>`:

```html
<body>
    <style>
        #body-wrapper {background-color: #eee; height: auto; width: 100%;}
        .container {padding: 20px;}
        ul {list-style-type: none; margin: 0; padding: 0;}
        li {padding: 10px 0;}
    </style>
    <div id="body-wrapper">
        <div id="container-1" class="container">
            <ul>
                <li><a href="#" class="link_1">Remove mobile</a></li>
            </ul>
        </div>
    </div>
</body>
```

When I click on the *Remove mobile* link, it removes the classes. Can you create a test page and see if this works for you?

**Comment by obihill** [comment]
So, I'll close this for now, but reopen if you still have issues.
