### ISSUE TITLE
turbo_classes not working

### ISSUE THREAD

**Issue by dhanjugopi** [obihill/restive.js#32]
I added the following code but i dont see the turbo classes, tried in iphone andriod phones tablets  :
$('body').restive({
            breakpoints: ['10000'],
            classes: ['nb'],
            turbo_classes: 'is_mobile=r_mobi,is_phone=r_phone,is_tablet=r_tablet,is_landscape=r_landscape',
            force_dip: true
        });

**Comment by obihill** [comment]
I tried your code on a test page and it's working fine.

Can you show me enough code to replicate your issue?
